### ISSUE TITLE
Some commands I want

### ISSUE THREAD

**Issue by txtsd** [PolyMC/bot#1]
A few commands like

- [x] `!paths` which will print the data directory paths
- [x] `!diff` which will print the two links we send when someone asks how is PolyMC different from MultiMC
- [x] `!forge` which will print info about the current CurseForge mods fiasco
- [ ] `!java` for links to specific java problems that people have

Feel free to add any more that we might need.

**Comment by ryanccn** [comment]
Gotcha

**Comment by DioEgizio** [comment]
what about a !curseforge ?

**Comment by DioEgizio** [comment]
also a !nvidiaflatpak for people having issues with nvidia drivers on flatpak

**Comment by ryanccn** [comment]
> what about a !curseforge ?

yes I added aliases

**Comment by ryanccn** [comment]
> also a !nvidiaflatpak for people having issues with nvidia drivers on flatpak

more details pls I don't know what that is (i.e. problem / solution)

**Comment by DioEgizio** [comment]
![IMG_20220521_102743](https://user-images.githubusercontent.com/83089242/169643127-048a7a4d-aeab-4389-9aaa-5f3e190688e9.jpg)

**Comment by DioEgizio** [comment]
>  !forge which will print info about the current CurseForge mods fiasco

forge != curseforge, kinda misleading

**Comment by txtsd** [comment]
> > !forge which will print info about the current CurseForge mods fiasco
> 
> forge != curseforge, kinda misleading

Oh just `!cf` should be fine then

**Comment by DioEgizio** [comment]
Btw I think !java can just link to https://polymc.org/wiki/getting-started/installing-java/
